version: '3.7'
services:
    nginx:
        image: 'nginx:1.25-alpine'
        container_name: panel.nginx
        restart: unless-stopped
        ports:
            - '85:80'
        environment:
            - TZ=Europe/Istanbul
        volumes:
            - '.runtime/docker/nginx/logs:/var/log/nginx'
            - './docker/initial/nginx/conf:/etc/nginx/conf.d'
            - './:/var/www'
        depends_on:
            - php
    mysql:
        platform: linux/amd64
        image: 'mysql:8.0.30'
        container_name: panel.mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: lara
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: user
            MYSQL_USER: user
        ports:
            - '3306:3306'
        volumes:
            - './runtime/docker/mysql/data:/var/lib/mysql'
            - './docker/initial/mysql/conf:/etc/mysql/conf.d'
    php:
        build: ./docker/initial/php
        container_name: panel.php
        restart: unless-stopped
        depends_on:
            - mysql
        environment:
            - PHP_DIR_OWNER=1000
            - RUN_USER=1000
        volumes:
            - '.:/var/www'
            - './runtime/docker/php/data:/var/php'
volumes:
    sail-mysql:
        driver: local
